### ISSUE TITLE
[Bug]: [v2] Loading speed regression in betas

### ISSUE THREAD

**Issue by pryley** [mgmeyers/obsidian-kanban#938]
### Describe the bug

Rendering of cards in kanban boards is noticeably slower in the v2 betas. 

https://github.com/mgmeyers/obsidian-kanban/assets/134939/531df5a8-6d70-4615-9d05-ebd054d98602

### Expected Behavior

Rendering of cards seemed faster in the v1.* releases.

### Steps to reproduce

The kanban board in the screen recording has 14 lanes with ~200 cards in total.

### Operating system

macOS

**Comment by mgmeyers** [comment]
@pryley Unfortunately this is a tradeoff that came with better support for things like rendering dataview queries in cards. I tried to make it as performant as possible on my end but the bottleneck is largely Obsidian's markdown renderer. I'm definitely open to PRs if folks want to explore further performance improvements.

**Comment by pryley** [comment]
Ah, makes sense. You can close this issue if you like.

**Comment by pjeby** [comment]
Raw speed is a bit less of an issue than it blocking the event loop.  Some of my boards block the app entirely for five seconds or more, even while hover-previewing them (where the event loop block is a bigger issue should you happen to hover the wrong board, as it keeps you from hovering *away*).

Is there any way for it to pause every so many milliseconds of rendering with a setTimeout(0)?  That would allow the event loop to proceed during the loading, even if the rendering has to be done in the UI thread.

Or is the issue that it's passing to Obsidian's rendering queue and Obsidian empties it synchronously?  It looks like Obsidian defaults to synchronous parsing for text <10k in size.  Given its normal use, that makes sense, but here where it's going to render hundreds of items it doesn't make as much sense.  I suspect that if there were a way to tell it to use the async parser, it would resolve the UI blocking issue, since interacting with the worker should allow the event loop to proceed.  (It *might* even speed things up, though I doubt it.)

Another possibility would be to scan card text for to make sure there's no syntax that requires the full parser (code blocks, tables, checklists, headings, dataview inlines) and use a "flat" rendering (i.e. the 1.x way of doing it) if possible.

It's been a while since I looked at the plugin's insides, but I might have a look at one or two of the above when I get a chance.  It seems to me that a big part of the performance penalty might be the part where Obsidian is expecting to be managing virtual renderings/scroll windowing and a bunch of other heavy-duty stuff, for every single card.  So not doing it for most cards might save a ton of time and memory on larger boards - i.e., it should be almost as fast as the old version in fact, unless nearly every card is a dataview or table or something.

**Comment by mgmeyers** [comment]
So, just a couple of things to note if you want to dig into this (and apologies in advance for the sloppy code you're likely to encounter).

There is a mechanism in place for throttling the rendering of cards, but I had a hard time finding the right balance between not blocking the UI and not making the board take forever to fully load.

https://github.com/mgmeyers/obsidian-kanban/blob/edad5d631d28dfde402d6f8e0d0d777021587292/src/KanbanView.tsx#L50-L53

Also, I disabled some features from the base renderer that were slowing things down:

https://github.com/mgmeyers/obsidian-kanban/blob/edad5d631d28dfde402d6f8e0d0d777021587292/src/components/MarkdownRenderer/MarkdownRenderer.tsx#L252-L255

And I implemented a weird caching system that prevents cards from being rerendered unless their content changes.

https://github.com/mgmeyers/obsidian-kanban/blob/edad5d631d28dfde402d6f8e0d0d777021587292/src/components/MarkdownRenderer/MarkdownRenderer.tsx#L477-L487

On another note, It might be challenging to know if a card needs to be post-processed. For example, this card would need to be post-processed if my pandoc reference list plugin was enabled `blah blah blah @citationKey`. Correct post-processing is the reason I switched to the full preview renderer, but I wonder if there's a way to do this with the old static renderer so we're not getting any unnecessary functionality?

Another thought that I had but haven't had the wherewithal to explore is running the board through the preview renderer as a single document during the initial load, and then pulling out the DOM corresponding to each card.

**Comment by pjeby** [comment]
In principle the static render *does* allow postprocessing -- after all, 1.x *does* support preprocessing.  It just doesn't ever *update* anything dynamic.

Could it be that the problem before was that cloneNode was used on a cached version of the rendering?  If so, dynamic updates would've applied only to the cached DOM and not the real one, and it *should* be possible to use the static renderer instead, provided you don't cache-and-clone the result.  (And of course that the Component passed to render() is unloaded when the card text changes.)

**Comment by mgmeyers** [comment]
So it turns out my knowledge of Obsidian's markdown rendering API was out of date and I was rendering markdown all wrong. I've implemented a new markdown renderer that should be a lot faster than the old one. Test out `2.0.36-beta` and let me know if this seems better to you two.

**Comment by pryley** [comment]
Noticeably faster!

**Comment by pjeby** [comment]
It's about 3x faster, but still hangs the UI thread - worse, it does it *before* rendering, so opening the board or viewing in a hover editor visibly stalls for a couple seconds before anything at all appears.  The advantage of the "new" way in 2.x was that you got a board w/lots of empty cards immediately.  So if there's a way to still do that and also not hog the UI thread, that'd be super.  But this is definitely a lot faster!  The hang just feels (comparatively) worse because there's nothing on screen during e.g. hovering a link to a board.

Comparing side by side with the old version, the new version appears *slightly* slower than 1.x for the same board, but not by much.  So it's probably fast enough now to use.  It just would be excellent if the board rendered first (or showed a loading indicator) so you at least have something to look at while the UI hangs.  :wink:

**Comment by mgmeyers** [comment]
Give `2.0.37-beta` a go. Boards now render in three stages to prevent bottle necks: parsing, prerendering of card markdown, then rendering the react tree.

**Comment by pjeby** [comment]
Excellent!  It's faster and doesn't block the UI for more than a second now.  It does block Hover Editor from popping up until the board is fully rendered, which still takes about 2 seconds.  (Which is odd because ISTM it shouldn't need to *do* anything that would block when the view is opened.  I keep trying to spot where it happens in the debugger and not finding it.)

Still, it now is pretty close to the old performance and amount of blocking, so awesome!
